### PR TITLE
unescape punctuation in toc item title

### PR DESCRIPTION
**Pull request by stephenafamo**

### CODE REVIEW

**Comment by abhinav** [comment]
Thanks for the patch, @stephenafamo!
Would you mind adding a test case to https://github.com/abhinav/goldmark-toc/blob/main/testdata/tests.txt to cover the case this is trying to protect against, please?
Thanks!

**Comment by stephenafamo** [comment]
Added @abhinav

**Review by abhinav — APPROVED** [review]
Thanks!

**Comment by abhinav** [comment]
@stephenafamo Looks like this change doesn't affect that test case?
I checked it out and reverted the code change. The test still passes.

```
% gh pr checkout 5
% git checkout main -- inspect.go
% go test
PASS
ok      github.com/abhinav/goldmark-toc 0.042s
```

I'm digging into it more but if you have a more specific failure case, that would be great.

**Review by abhinav — CHANGES_REQUESTED** [review]
I tried with '#' as the punctuation as well.
It works fine without this change.
Are you sure we need to handle the escaping?

**Comment by abhinav** [comment]
I think I found the failing case. It's more in the TOC returned by inspect rather than the rendering.

**Review by abhinav — APPROVED** [review]
The new test case in inspect_test validates this issue.
It makes sense that when you inspect, the returned TOC has the unescaped titles.

**Comment by stephenafamo** [comment]
Nice work. Sorry for not checking if the tests were testing the correct thing 😅

**Pull request merged**
